--- #YAML:1.0
name:                DateTimeX-AATW
version:             0.04
abstract:            Module abstract (<= 44 characters) goes here
license:             ~
author:              
    - Kevin C. McGrath (kmcgrath@baknet.com)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    DateTime:                      0.5
    DateTime::TimeZone:            0.91
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
